#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : R-qpdf
Version  : 1.3.3
Release  : 43
URL      : https://cran.r-project.org/src/contrib/qpdf_1.3.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/qpdf_1.3.3.tar.gz
Summary  : Split, Combine and Compress PDF Files
Group    : Development/Tools
License  : Apache-2.0
Requires: R-qpdf-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-askpass
Requires: R-curl
BuildRequires : R-Rcpp
BuildRequires : R-askpass
BuildRequires : R-curl
BuildRequires : buildreq-R
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(zlib)

%description
as split, combine, and compress. This package interfaces directly to the 'qpdf' 
    C++ API and does not require any command line utilities. Note that 'qpdf' does

%package lib
Summary: lib components for the R-qpdf package.
Group: Libraries

%description lib
lib components for the R-qpdf package.


%prep
%setup -q -n qpdf
pushd ..
cp -a qpdf buildavx2
popd
pushd ..
cp -a qpdf buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711508350

%install
export SOURCE_DATE_EPOCH=1711508350
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/qpdf/DESCRIPTION
/usr/lib64/R/library/qpdf/INDEX
/usr/lib64/R/library/qpdf/Meta/Rd.rds
/usr/lib64/R/library/qpdf/Meta/features.rds
/usr/lib64/R/library/qpdf/Meta/hsearch.rds
/usr/lib64/R/library/qpdf/Meta/links.rds
/usr/lib64/R/library/qpdf/Meta/nsInfo.rds
/usr/lib64/R/library/qpdf/Meta/package.rds
/usr/lib64/R/library/qpdf/NAMESPACE
/usr/lib64/R/library/qpdf/NEWS
/usr/lib64/R/library/qpdf/R/qpdf
/usr/lib64/R/library/qpdf/R/qpdf.rdb
/usr/lib64/R/library/qpdf/R/qpdf.rdx
/usr/lib64/R/library/qpdf/help/AnIndex
/usr/lib64/R/library/qpdf/help/aliases.rds
/usr/lib64/R/library/qpdf/help/paths.rds
/usr/lib64/R/library/qpdf/help/qpdf.rdb
/usr/lib64/R/library/qpdf/help/qpdf.rdx
/usr/lib64/R/library/qpdf/html/00Index.html
/usr/lib64/R/library/qpdf/html/R.css
/usr/lib64/R/library/qpdf/tests/testthat.R
/usr/lib64/R/library/qpdf/tests/testthat/pdf-example-password.original.pdf
/usr/lib64/R/library/qpdf/tests/testthat/test-password-callback.R
/usr/lib64/R/library/qpdf/tests/testthat/test-rotate.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/qpdf/libs/qpdf.so
/V4/usr/lib64/R/library/qpdf/libs/qpdf.so
/usr/lib64/R/library/qpdf/libs/qpdf.so
